export const ENV = {
  REMOVE_BG_API_KEY: process.env.REMOVE_BG_API_KEY,
  UPLOADTHING_TOKEN: process.env.UPLOADTHING_TOKEN,
  CLOUDINARY: {
    CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
    API_KEY: process.env.CLOUDINARY_API_KEY,
    API_SECRET: process.env.CLOUDINARY_API_SECRET,
  },
  PORT: process.env.PORT || 3001,
  REDIS_URL: process.env.REDIS_URL || 'redis://localhost:6379',
  BULLMQ_PREFIX: process.env.BULLMQ_PREFIX || 'blue',
  DATABASE_URL: process.env.DATABASE_URL,
  ADMIN_TOKEN: process.env.ADMIN_TOKEN,
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
  PUBLISH_MODE: process.env.PUBLISH_MODE || 'manual',
  STORAGE: {
    DRIVER: process.env.STORAGE_DRIVER || 'local',
    S3_BUCKET: process.env.S3_BUCKET,
    S3_REGION: process.env.S3_REGION,
    S3_ENDPOINT: process.env.S3_ENDPOINT,
    S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID,
    S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY,
  },
  CLIPFORGE_CONCURRENCY: {
    SCRIPT: Number(process.env.CLIPFORGE_SCRIPT_CONCURRENCY || 5),
    TTS: Number(process.env.CLIPFORGE_TTS_CONCURRENCY || 5),
    RENDER: Number(process.env.CLIPFORGE_RENDER_CONCURRENCY || 3),
    POST: Number(process.env.CLIPFORGE_POST_CONCURRENCY || 2),
    METRICS: Number(process.env.CLIPFORGE_METRICS_CONCURRENCY || 2),
  },
};
